name: 'Auto assign PR'
description: 'Auto assign PR to the creator'
author: '@delivery-much'
branding:
  icon: 'code'
  color: 'yellow'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'